### PR TITLE
Align type specs with actual katt_callback implementation

### PR DESCRIPTION
**Pull request by dszoboszlay**

### CODE REVIEW

**Comment by dszoboszlay** [comment]
@massemanet, @dmitriid: could either of you please review and preferably merge this PR?

**Comment by andreineculau** [comment]
You can also switch to for-get/katt where this project is actually maintained :)
Can't check now but i bet your changes are redundant there (i.e. fixed already)

**Comment by dszoboszlay** [comment]
I actually want to get the changes into Klarna's internal `katt` fork on Stash. And that repo seems to be still tracking this open source repo, not the `for-get/katt`. This approach worked for #5 for example a couple of months ago. But if you say this repo is completely dead, I can also open my PR in Stash.

**Comment by andreineculau** [comment]
Ahh, then ignore me :) I am not working at Klarna anymore and I don't know
the anything about the current setup (but it sounds dead wrong if in order
to push a change internally, you need to push it to the external upstream)

On Fri, Sep 25, 2015 at 10:50 AM, Dániel Szoboszlay <
notifications@github.com> wrote:

> I actually want to get the changes into Klarna's internal katt fork on
> Stash. And that repo seems to be still tracking this open source repo, not
> the for-get/katt. This approach worked for #5
> https://github.com/klarna/katt/pull/5 for example a couple of months
> ago. But if you say this repo is completely dead, I can also open my PR in
> Stash.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/klarna/katt/pull/6#issuecomment-143163270.

## 

andreineculau.com http://www.andreineculau.com

**Comment by dszoboszlay** [comment]
Well, if the change is to an open source branch - as in this case - I was told to first get the change merged upstream then pull it into the internal repo. But I can go the other way round too and open the PR against Stash.

**Comment by andreineculau** [comment]
Aha.
If you know, or anyone that works at Klarna sees this - I'd be interested
in how that is setup up.
- An add-on? I didn't find anything
- something inhouse ? like a cronjob, or a hook á la gitolite's upstream
  trigger
  https://github.com/sitaramc/gitolite/blob/master/src/triggers/upstream ?

On Fri, Sep 25, 2015 at 11:24 AM, Dániel Szoboszlay <
notifications@github.com> wrote:

> Well, if the change is to an open source branch - as in this case - I was
> told to first get the change merged upstream then pull it into the internal
> repo. But I can go the other way round too and open the PR against Stash.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/klarna/katt/pull/6#issuecomment-143168722.

## 

andreineculau.com http://www.andreineculau.com

**Comment by keis** [comment]
I don't know about this specific case but I don't know of any fancy tool being used for this kinda of stuff. My guess it's someone doing a manual fetch -> push to sync the repos up

**Comment by dszoboszlay** [comment]
In the meantime I opened this PR and got it merged in the internal Stash repo. So there's no point in merging it here too, that would just cause merge conflicts.

**Comment by andreineculau** [comment]
Tack, David!

On Thu, Oct 15, 2015 at 10:19 AM, Dániel Szoboszlay <
notifications@github.com> wrote:

> In the meantime I opened this PR and got it merged in the internal Stash
> repo. So there's no point in merging it here too, that would just cause
> merge conflicts.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/klarna/katt/pull/6#issuecomment-148314938.

## 

andreineculau.com http://www.andreineculau.com

**Pull request closed without merging**
